version: "3"
services:
  etrobo-docker:
    build: .
    command: sleep infinity
    volumes:
      - ../:/home/hrp2/sdk/workspace/product
      - ~/.gitconfig:/home/etrobo/.gitconfig
      - ./.bashrc:/home/etrobo/.bashrc
    environment:
      SHELL: "/bin/bash"
      HOME: "/home/etrobo"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined